### ISSUE TITLE
Error wenn das Contao-News-Bundle nicht installiert ist

### ISSUE THREAD

**Issue by srhinow** [heimrichhannot/contao-categories-bundle#14]
**Context**
Contao version: 4.9.13
Bundle version: 1.1.1
PHP version: 7.3

**Description**
Da in einer Installation die Module wie Contao-News etc nicht gebraucht werden, wurden diese deinstalliert. z.B beim CronJob erzeugt dann aber "contao-categories-bundle" einen Critical Error:
![grafik](https://user-images.githubusercontent.com/741418/116206029-a734d300-a73e-11eb-9497-421511434c4d.png)

Da müsste dann doch eine Abfrage rein ob dieses Modul überhaupt exisitert oder nicht?

**Comment by Defcon0** [comment]
Fixed in 1.1.2 :-) Danke fürs Reporten!
