### ISSUE TITLE
Warning: Undefined array key "disabled"

### ISSUE THREAD

**Issue by jennrei** [heimrichhannot/contao-categories-bundle#15]
https://github.com/heimrichhannot/contao-categories-bundle/blob/cde5b3e8829582784c42fa48ce3bab498ce753d0/src/Widget/CategoryTree.php#L119

**Comment by koertho** [comment]
Hier müsste ein Abfrage, am besten mit Null coalescing operator, um das disabled rein. Rückfallwert wäre einfach false
