### ISSUE TITLE
Fehler beim "Neue Benutzergruppe" 

### ISSUE THREAD

**Issue by srhinow** [heimrichhannot/contao-categories-bundle#4]
Erweiterung. Ich wollte eine benutzergruppe für die API-Benutzer anlegen. Dabei ist folgender Error aufgetreten:
```
Attempted to load class "ChoiceType" from namespace "HeimrichHannot\FilterBundle\Filter\Type".
Did you forget a "use" statement for "Symfony\Component\Form\Extension\Core\Type\ChoiceType"?
```
Die use-Klasse: 
`use "HeimrichHannot\FilterBundle\Filter\Type\ChoiceType" `
gibt es auch gar nicht. Wenn ich in der "HeimrichHannot\CategoriesBundle\Filter\Type\CategoryChoiceType" den Symfony-namespace
`use Symfony\Component\Form\Extension\Core\Type\ChoiceType;`
 bekannt gebe, ist zu mindest der Fehler weg.

**Comment by Defcon0** [comment]
Tritt das auch mit PHP 7.3 auf?

**Comment by srhinow** [comment]
Ja es tritt auch bei PHP 7.3 auf, die Filter-Erweiterung wird ja auch nicht von den contao-category-bundle und contao-api-bundle required. Daher gibt es die Erweiterung contao-filter-bundle so ohne weiteres nicht im System und die referenzierte Klasse wird nicht gefunden.

**Comment by Defcon0** [comment]
Mhm, das Ding ist, das contao-filter-bundle definitiv keine harte Abhängigkeit von contao-categories-bundle sein sollte. Es ist eher eine lose Kopplung.

Ich habe es so angepasst, dass es keine Fehler mehr wirft. Sollte in 1.0.0-beta25 gefixt sein.
