### ISSUE TITLE
Reihenfolge der Kategorien im Frontend

### ISSUE THREAD

**Issue by arboc** [heimrichhannot/contao-categories-bundle#7]
Die Reihenfolge der Kategorien im Frontend entspricht nicht der im Backend angelegten Reihenfolge.

**Comment by Defcon0** [comment]
Wie gibbst du die Kategorien denn im Frontend aus?

**Comment by arboc** [comment]
Ich nutze das CategoriesMenu Modul der Erweiterung mit dem standard Navigations Template.  
Die Kategorien werden in der Reihenfolge der Eingabe angezeigt.

**Comment by arboc** [comment]
Ich vermute das liegt daran, dass in der Methode `findCategoryAndSubcategoryByPidAndIds`im `CategoryManager` das dem SQL-Statement ein `ORDER BY` fehlt:

```php
$objCategories = \Database::getInstance()->prepare('SELECT c1.*, (SELECT COUNT(*) FROM tl_category  c2 WHERE c2.pid=c1.id AND c2.id IN ('.implode(',', array_map('intval', $arrIds)).')) AS subcategories FROM tl_category c1 WHERE c1.pid=? AND c1.id IN ('.implode(',', array_map('intval', $arrIds)).')')->execute($pid);
```
